/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackGround: typeof import('./src/components/BackGround.vue')['default']
    GoogleMaps: typeof import('./src/components/GoogleMaps.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LanguageSwitcher: typeof import('./src/components/utils/LanguageSwitcher.vue')['default']
    Puntos: typeof import('./src/components/Puntos.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleDark: typeof import('./src/components/utils/ToggleDark.vue')['default']
  }
}
