/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IAkarIconsCalculator: typeof import('~icons/akar-icons/calculator')['default']
    'IBi:dashCircle': typeof import('~icons/bi/dash-circle')['default']
    IBiMoonFill: typeof import('~icons/bi/moon-fill')['default']
    IBiSunFill: typeof import('~icons/bi/sun-fill')['default']
    IGgAdd: typeof import('~icons/gg/add')['default']
    'IZondicons:minusOutline': typeof import('~icons/zondicons/minus-outline')['default']
    LanguageSwitcher: typeof import('./src/components/utils/LanguageSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleDark: typeof import('./src/components/utils/ToggleDark.vue')['default']
  }
}
